# fly.toml file generated for news-scraper-analyzer on 2022-01-27T21:15:46+01:00

app = "news-scraper-analyzer"

kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[build]
  builder = "heroku/buildpacks:20"

[env]
  PORT = "8080"
  NODE_ENV = "production"

[experimental]
  allowed_public_ports = []
  auto_rollback = true